// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNoUZ06fSrRu6TWccIwaHKxZ8FZdQbkks',
    appId: '1:64194742038:web:d63a052213de4eb9657237',
    messagingSenderId: '64194742038',
    projectId: 'fire-setup-55e8c',
    authDomain: 'fire-setup-55e8c.firebaseapp.com',
    storageBucket: 'fire-setup-55e8c.firebasestorage.app',
    measurementId: 'G-PMGSZBPMW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ydQF9qROV5pTCWBz33Df0Q_LkXrZ2xA',
    appId: '1:64194742038:android:874202460ffff842657237',
    messagingSenderId: '64194742038',
    projectId: 'fire-setup-55e8c',
    storageBucket: 'fire-setup-55e8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvqxzrOec4aoBSYy6fD3NpAJH0HBed9Q',
    appId: '1:64194742038:ios:d61b782dc7a9a48f657237',
    messagingSenderId: '64194742038',
    projectId: 'fire-setup-55e8c',
    storageBucket: 'fire-setup-55e8c.firebasestorage.app',
    iosBundleId: 'com.example.taskflows',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvqxzrOec4aoBSYy6fD3NpAJH0HBed9Q',
    appId: '1:64194742038:ios:d61b782dc7a9a48f657237',
    messagingSenderId: '64194742038',
    projectId: 'fire-setup-55e8c',
    storageBucket: 'fire-setup-55e8c.firebasestorage.app',
    iosBundleId: 'com.example.taskflows',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNoUZ06fSrRu6TWccIwaHKxZ8FZdQbkks',
    appId: '1:64194742038:web:2547fdad16c62622657237',
    messagingSenderId: '64194742038',
    projectId: 'fire-setup-55e8c',
    authDomain: 'fire-setup-55e8c.firebaseapp.com',
    storageBucket: 'fire-setup-55e8c.firebasestorage.app',
    measurementId: 'G-EMNRH0XT1D',
  );
}
